import Battery from './Battery.js';
import Remote from './Remote.js';

let remote=new Remote();
let battery1=new Battery();
let battery2=new Battery();

remote.setBattery(battery1,battery2);
remote.getStatus();
remote.turnOn();
remote.turnOn();
remote.turnOff();
remote.turnOff();
remote.getStatus();
remote.turnOn();
remote.getStatus();
remote.turnOff();
remote.turnOn();
remote.turnOff();
remote.turnOn();
remote.turnOff();
remote.turnOn();
remote.turnOff();
remote.turnOn();
remote.turnOff();
remote.turnOn();
remote.turnOff();
remote.turnOn();
remote.turnOff();
remote.turnOn();
remote.turnOff();
remote.turnOn();
remote.turnOff();
remote.getStatus();
remote.hasCharge();
